### ISSUE TITLE
need more comments and a README

### ISSUE THREAD

**Issue by dpnkrpl** [kevinjycui/bad-apple#3]
This repository itself is very interesting (even without the youtube reference) , add a readme , how to guide and make the code more readable with comments.

**Comment by toydotgame** [comment]
Personally, I think the `Astolfo/` directory is something that should become open-source, for the good of the world.

**Comment by dpnkrpl** [comment]
I think the author is not interested in doing so.
closing.

**Comment by toydotgame** [comment]
This repo serves primarily as an archive of code, rather than a proper project. Source-available rather than open-source.
(That's what I think)
