### ISSUE TITLE
Loading of files into memory

### ISSUE THREAD

**Issue by Jark5455** [kevinjycui/bad-apple#7]
I know this is a meme and stuff, but I was wondering why you would load all of the images into memory before running, instead of using a BufferedReader

**Comment by umutsevdi1** [comment]
I'm new at JavaScript & NodeJS, so I didn't even know it was a thing. I've been learning it for 2 weeks now. I built it just to have fun, and test stuff. Thanks for the advice.

**Comment by toydotgame** [comment]
With such a downscaled version of the Bad Apple!! video being used, this wouldn't be much of a problem for using too much memory.
Possibly it's just a bit faster to load it all at the start rather than as you go along. These things take ages to execute, anyway.

**Comment by Jark5455** [comment]
@toydotgame, really, I thought memory was the biggest issue that was causing the low performance, my system reported ~8 GiB memory usage, and most was forced onto a swap file.

**Comment by toydotgame** [comment]
Which specific port is this? I've run a few from this repo on my Arch box and I've had only a few megabytes used.

**Comment by kevinjycui** [comment]
It just hasn't ever been an issue for me. Loading them on Ubuntu or Windows (especially when they are downscaled bitmaps) hasn't had a real effect on performance. Sorry for the late response.
